# set prefix keys to alt + space
set -g prefix M-Space

# turn mouse support on
set -g mouse on

# set vim keybinds 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# some settings
set -sa terminal-overrides ",xterm*:Tc"

# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Resize panes using Ctrl + Shift + h/j/k/l
bind -n C-H resize-pane -L 5  # Ctrl+Shift+H to resize left
bind -n C-J resize-pane -D 5  # Ctrl+Shift+J to resize down
bind -n C-K resize-pane -U 5  # Ctrl+Shift+K to resize up
bind -n C-L resize-pane -R 5  # Ctrl+Shift+L to resize right

# unbind the r key and set it to prefix + r to reload tmux configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.config/tmux/tmux.conf" 


